// angular/src/app/image-selector/image-selector.component.ts
import { Component, Inject } from '@angular/core';
import { Observable } from 'rxjs';
import { map, combineLatest } from 'rxjs/operators';

import { Store } from '../state/Store';
import { AppState, Image } from '../app.state';
import { AppActions } from '../app-actions.service';

@Component({
  selector: 'app-image-selector',
  templateUrl: './image-selector.component.html',
  styleUrls: ['./image-selector.component.css']
})
export class ImageSelectorComponent {
  readonly activeImage$: Observable<Image | null> = this.store.select('activeImage');

  readonly images$: Observable<(Image & { isActive: boolean })[]> = this.store.select('images')
    .pipe(
      combineLatest(this.activeImage$),
      map(([ images, activeImage ]) => images.map(image => ({
        ...image,
        isActive: Boolean(activeImage && activeImage.url === image.url)
      }))));

  constructor(
    @Inject(Store) private store: Store<AppState>,
    @Inject(AppActions) private actions: AppActions
  ) {}

  onImageClick(image: Image): void {
    this.actions.setActiveImage(image);
  }
}

<div class="image-thumbnail" *ngFor="let image of image$ | async" [class.active]="image.isActive">
  <img [src]="image.url" (click)="onImageClick(image)" />
</div>

// react/src/ImageSelector.tsx
import React from 'react';

import { AppState, Action, ActionType } from './state';

export function ImageSelector(props: { state: AppState, dispatch: React.Dispatch<Action> }): JSX.Element {
  return (
    <image-selector>
      {props.state.images.map((image, index) => (
        <div
          className={`image-thumbnail ${props.state.activeImage === index ? 'active' : ''}`.trim()}>
          <img src={image.url} onClick={() => props.dispatch({ type: ActionType.SELECTED_IMAGE_CHANGED, payload: index })} />
        </div>
      ))}
    </image-selector>
  );
}
